# as we're building `{{ compiler("cuda") }}` itself here, we need to specify
# the versions ourselves, which means overriding the mega-zip from the pinning

cuda_compiler:  # [linux64 or win or (linux and ppc64le) or (linux and aarch64)]
  - nvcc        # [linux64 or win or (linux and ppc64le) or (linux and aarch64)]

cuda_compiler_version:
  - 11.8   # [linux64 or win or (linux and ppc64le) or (linux and aarch64)]

c_compiler_version:  # [os.environ.get("BUILD_PLATFORM", "").startswith("linux")]
  - 7  # [os.environ.get("BUILD_PLATFORM") == "linux-64"]
  - 8  # [os.environ.get("BUILD_PLATFORM") == "linux-ppc64le"]
  - 8  # [os.environ.get("BUILD_PLATFORM") == "linux-aarch64"]

cxx_compiler_version:  # [os.environ.get("BUILD_PLATFORM", "").startswith("linux")]
  - 7  # [os.environ.get("BUILD_PLATFORM") == "linux-64"]
  - 8  # [os.environ.get("BUILD_PLATFORM") == "linux-ppc64le"]
  - 8  # [os.environ.get("BUILD_PLATFORM") == "linux-aarch64"]

docker_image:                                   # [os.environ.get("BUILD_PLATFORM", "").startswith("linux-")]
  - quay.io/condaforge/linux-anvil-cuda:11.8    # [linux64 and os.environ.get("BUILD_PLATFORM") == "linux-64"]
  - quay.io/condaforge/linux-anvil-ppc64le-cuda:11.8   # [linux and ppc64le and os.environ.get("BUILD_PLATFORM") == "linux-ppc64le"]
  - quay.io/condaforge/linux-anvil-aarch64-cuda:11.8   # [linux and aarch64 and os.environ.get("BUILD_PLATFORM") == "linux-aarch64"]

cudnn:
  - 8      # [linux64 or win]           # CUDA 11.8
  - undefined   # [linux and ppc64le]        # CUDA 11.8
  - undefined   # [linux and aarch64]        # CUDA 11.8

cdt_name:  # [linux]
  - cos7   # [linux64]                  # CUDA 11.8
  - cos7   # [linux and ppc64le]        # CUDA 11.8
  - cos7   # [linux and aarch64]        # CUDA 11.8

cross_target_platform:
  - linux-64        # [linux and x86_64]
  - linux-aarch64   # [linux and (x86_64 or aarch64)]
  - linux-ppc64le   # [linux and (x86_64 or ppc64le)]
  - win-64          # [win and x86_64]
